print()
print('Please enter the following information :')
first=input('First Name: ')
last=input('Last Name: ')
mail=input('Email address: ')
phone=input('Phone Number: ')
job=input('Job Title: ')
id=input ('ID Number: ')
hair=input ('Hair Color: ')
eyes=input ('Eyes Color: ')
month=input ('Starting Month :')
training=input('Completed additional training: ')



print()
print('The ID Card is:')
print('----------------------------------------------')
print(f'{last.upper()},{first.capitalize()}')
print(f'{job.title()}')
print(f'ID: {id}')
print()
print(mail.lower())
print(phone)
print()
print(f'Hair: {hair.capitalize():15} Eyes: {eyes.capitalize()}')
print(f'Month: {month.capitalize():15} Training: {training.capitalize()}')
print('----------------------------------------------')