print()
print('Please enter the following :' )
print()
adj=input('adjetive: ')
ani=input('animal: ')
ver1=input('verb: ')
excla=input('exclamation: ')
ver2=input('verb: ')
ver3=input('verb: ')
color=input('color: ')
thing = input('thing :')
place = input('place : ')
person= input('person: ')
adj1 = input('another adjactive : ')
insect= input('insect : ')
food = input('food : ')
print()
print('Your story is: ')
print()
print ('The other day, I was really in trouble. It all started when I saw a very' )
print (f'{adj} {ani.capitalize()} {ver1} down the hallway. "{excla.capitalize()}!" I yelled. But all')
print (f'I could think to do was to {ver2} over and over. Miraculously,')
print (f'that caused it to stop, but not before it tried to {ver3}')
print (f'right in front of my family.')
print()
print ('Another story is: ')
print(f'Last night I dreamed I was a  {adj1}  butterfly with {color}')
print(f'splocthes that looked like {thing}  .I flew to   {place} with my bestfriend and ')
print(f'{person.capitalize()} who was a {adj}  {insect.capitalize()} .We ate some {food}  when we got')
print(f'there and then decided to {ver3} and the dream ended when I said-- lets {ver1} .')
print()